stages:
  - test
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

test:
  stage: test
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false"]
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  script:
    - cd infra/docker
    - docker-compose run django python manage.py test

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false"]
  before_script:
    - apk add --no-cache docker-compose
    - docker info
  script:
    - cd infra/docker
    - docker-compose build
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache docker-compose
    - chmod +x ./infra/docker/scripts/deploy_alpine.sh
    - chmod +x ./infra/docker/scripts/health-check_alpine.sh
  script:
    - sh ./infra/docker/scripts/deploy_alpine.sh
