stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - cd infra/docker
    - docker-compose run django python manage.py test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
  script:
    - cd infra/docker
    - docker-compose build
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - chmod +x ./scripts/deploy.sh
  script:
    - cd infra/docker && ./scripts/deploy.sh
  environment:
    name: production
  only:
    - main
