{
 "title": "System Metrics - Node Exporter",
 "description": "CPU usage, Memory usage, DIsk Read Rate",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B * 100", "type": "math" }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "timeseries",
   "description": "Bytes read from disk per second across all devices",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}